library(shiny)
library(gsDesign)
library(SWSamp)
options(shiny.trace = TRUE)
# add text you want into the fluidpage command
ui <- navbarPage(title = "Sample Size Calculator",
###################### MEANS TAB #######################
             navbarMenu(title = "Comparison of Means",
                        tabPanel("Comparison of Means",
                                 titlePanel("Comparison of Means"),
                                 column(4,
                                        wellPanel(
                                          sliderInput(inputId = "siglevel", 
                                                      label = "Choose significance level (Type I error probability)",
                                                      value = 0.05, min = 0, max = 0.2, 
                                                      step = 0.005),
                                          sliderInput(inputId = "power", 
                                                      label = "Choose power", 
                                                      value = 0.800, 
                                                      min = 0.5, max = 1, 
                                                      step = 0.005),
                                          numericInput(inputId = "delta",
                                                       label = "Insert true difference in means", 
                                                       value = 0.8),
                                          numericInput(inputId = "sd",
                                                       label = "Insert standard deviation",
                                                       value = 1),
                                          selectInput(inputId = "type",
                                                      label = "Choose type of t test",
                                                      c("two.sample","one.sample",
                                                        "paired")),
                                          selectInput(inputId = "alt",
                                                      label = "Choose one- or two-sided test",
                                                      c("two.sided", "one.sided")),
                                          HTML(paste0(
                                            "<small>","<b>","Note:","</b>",
                                            " For clarification on any of the parameters,",
                                            " please refer to the 'Definitions' tab under the About menu.",
                                            "</small>")
                                          )
                                        )
                                 ),
                                 column(8,
                                        tags$b("Sample size per group:"),
                                        verbatimTextOutput(outputId = "samplesize_mean"),
                                        plotOutput(outputId = "powerplot_mean")
                                 )
                        ),
                        tabPanel("Comparison of Means with ANCOVA",
                                 titlePanel("Comparison of Means with ANCOVA"),
                                 column(4,
                                        wellPanel(
                                          sliderInput(inputId = "siglevel_an", 
                                                      label = "Choose significance level (Type I error probability)",
                                                      value = 0.05, min = 0, max = 0.2, 
                                                      step = 0.005),
                                          sliderInput(inputId = "power_an", 
                                                      label = "Choose power", 
                                                      value = 0.800, 
                                                      min = 0.5, max = 1, 
                                                      step = 0.005),
                                          numericInput(inputId = "delta_an",
                                                       label = "Insert true difference in means", 
                                                       value = 0.8),
                                          numericInput(inputId = "sd_an", 
                                                       label = "Insert standard deviation",
                                                       value = 1),
                                          sliderInput(inputId = "r2",
                                                      label = "Choose rho value (correlation between baseline and follow-up)",
                                                      value = 0.775, min = 0, max = 1, step = 0.005),
                                          selectInput(inputId = "type_an",
                                                      label = "Choose type of t test",
                                                      c("two.sample","one.sample",
                                                        "paired")),
                                          selectInput(inputId = "alt_an",
                                                      label = "Choose one- or two-sided test",
                                                      c("two.sided", "one.sided")),
                                          HTML(paste0(
                                            "<small>","<b>","Note:","</b>",
                                            " For clarification on any of the parameters,",
                                            " please refer to the 'Definitions' tab under the About menu.",
                                            "</small>")
                                          )
                                        )
                                 ),
                                 column(8,
                                        tags$b("Sample size per group for t-test:"),
                                        verbatimTextOutput(outputId = "samplesizean_mean"),
                                        tags$b("Sample size per group for ANCOVA:"),
                                        verbatimTextOutput(outputId = "samplesizean_mean_ancova"),
                                        plotOutput(outputId = "powerplotan_mean")
                                 )
                        )
             ),             
########################## PROPORTIONS TAB ##########################
           tabPanel("Comparison of Proportions",
                    titlePanel("Comparison of Proportions"),
                    # control panel
                    column(4,
                           wellPanel(
                             # slider panel for significance level
                             sliderInput(inputId = "siglevel_prop", 
                                         label = "Choose significance level (Type I error probability)",
                                         value = 0.05, min = 0, max = 0.2, 
                                         step = 0.005),
                             # slider panel for power
                             sliderInput(inputId = "power_prop", 
                                         label = "Choose power", 
                                         value = 0.800, 
                                         min = 0.5, max = 1, step = 0.005),
                             # select option for choosing proportion
                             selectInput(inputId = "prop_type",
                                         label = "Choose",
                                         c("risk difference",
                                           "odds ratio",
                                           "risk ratio",
                                           "relative risk reduction")),
                             # allows you to build the UI needed based on which option was chosen before in the server file
                             uiOutput("ui_prop"),
                             # text and slider panel for entering control probability (can match both bi-directionally in the server file)
                             tags$b("Use slider or text box to enter probability in control:"),
                             sliderInput(inputId = "control_slider",label = NULL,
                                         value = 0.75, min = 0, max = 1, 
                                         step = 0.001),
                             numericInput(inputId = "control_txt",label = NULL,
                                          value = 0.75,
                                          min = 0, max = 1),
                             # select panel for choosing one- or two-sided test
                             selectInput(inputId = "alt_prop", 
                                         label = "Choose one- or two-sided test",
                                         c("two.sided", "one.sided")),
                             HTML(paste0(
                               "<small>","<b>","Note:","</b>",
                               " For clarification on any of the parameters,",
                               " please refer to the 'Definitions' tab under the About menu.",
                               "</small>")
                               )
                             )
                           ),
                    column(8,
                           tags$b("Sample size per group:"),
                           verbatimTextOutput(outputId = "samplesize_prop"),
                           tags$b("Probability in intervention:"),
                           verbatimTextOutput(outputId = "type_prop"),
                           plotOutput(outputId = "powerplot_prop")
                           )
                    ),
####################### SURVIVAL TAB #####################
            tabPanel("Time-to-Event Analysis",
                     titlePanel("Time-to-Event Analysis"),
                     column(4,
                            wellPanel(
                              # slider panel for alpha
                              sliderInput(inputId = "alpha", 
                                          label = "Choose significance level (Type I error probability)",
                                          value = 0.025, min = 0, max = 0.2, 
                                          step = 0.005),
                              # slider panel for power
                              sliderInput(inputId = "power_surv", 
                                          label = "Choose power", 
                                          value = 0.900, 
                                          min = 0.5, max = 1, step = 0.005),
                              selectInput(inputId = "units",
                                          label = "Select time units",
                                          c("days","weeks","months","years"),
                                          selected = "months"),
                              # select option for choosing proportion
                              selectInput(inputId = "surv_type",
                                          label = "Choose",
                                          c("control hazard rate",
                                            "median survival")),
                              # allows you to build the UI needed based on which option was chosen before in the server file
                              uiOutput("ui_surv"),
                              numericInput(inputId = "hr",
                                           label = "Enter hazard ratio",
                                           value = 0.75,min = 0),
                              numericInput(inputId = "minfup",
                                           label = "Enter follow-up of last patient enrolled",
                                           value = 14,min = 0),
                              numericInput(inputId = "T",
                                           label = "Enter study duration",
                                           value = 36,min = 0),
                              numericInput(inputId = "R",
                                           label = "Enter patient recruitment duration",
                                           value = 12,min = 0),
                              # select panel for choosing one- or two-sided test
                              selectInput(inputId = "sided", 
                                          label = "Choose one- or two-sided test",
                                          c(1, 2)),
                              HTML(paste0(
                                "<small>","<b>","Note:","</b>",
                                " For clarification on any of the parameters,",
                                " please refer to the 'Definitions' tab under the About menu.",
                                "</small>"))
                              )
                            ),
                     column(8,
                            tags$b("Sample size per group:"),
                            verbatimTextOutput(outputId = "samplesize_surv"),
                            tags$b("Total sample size:"),
                            verbatimTextOutput(outputId = "tot_sample_surv"),
                            tags$b("Total number of events:"),
                            verbatimTextOutput(outputId = "events_surv"),
                            tags$b("Event hazard rate of the control group:"),
                            verbatimTextOutput(outputId = "lambdaC_surv")
                            )
                     ),
######################## CRT TAB ################################
           navbarMenu("Cluster Randomized Trials",
                      tabPanel("CRT (Means)",
                               titlePanel("Cluster Randomized Trials (Means)"),
                               column(4,
                                      wellPanel(sliderInput(inputId = "siglevel_crt", 
                                                            label = "Choose significance level (Type I error probability)",
                                                            value = 0.05, min = 0, max = 0.2, 
                                                            step = 0.005),
                                                sliderInput(inputId = "power_crt", 
                                                            label = "Choose power", 
                                                            value = 0.800, 
                                                            min = 0.5, max = 1, 
                                                            step = 0.005),
                                                numericInput(inputId = "delta_crt",
                                                             label = "Insert true difference in means", 
                                                             value = 0.8),
                                                numericInput(inputId = "sd_crt", 
                                                             label = "Insert standard deviation",
                                                             value = 1),
                                                numericInput(inputId = "clus_crtm",
                                                             label = "Insert average cluster size", 
                                                             value = 25),
                                                tags$b("Use slider or text box to enter intracluster correlation coefficient:"),
                                                sliderInput(inputId = "icc_crtm_slider",label = NULL,
                                                            value = 0.05, min = 0, max = 0.5, 
                                                            step = 0.001),
                                                numericInput(inputId = "icc_crtm_txt",label = NULL,
                                                             value = 0.05, 
                                                             min = 0, max = 0.5,step = 0.001),
                                                selectInput(inputId = "type_crt",
                                                            label = "Choose type of t test",
                                                            c("two.sample","one.sample",
                                                              "paired")),
                                                selectInput(inputId = "alt_crt",
                                                            label = "Choose one- or two-sided test",
                                                            c("two.sided", "one.sided")),
                                                HTML(paste0(
                                                  "<small>","<b>","Note:","</b>",
                                                  " For clarification on any of the parameters,",
                                                  " please refer to the 'Definitions' tab under the About menu.",
                                                  "</small>")
                                                  )
                                                )
                                      ),
                               column(8,
                                      tags$b("Sample size per group:"),
                                      verbatimTextOutput(outputId = "samplesize_mean_crt"),
                                      tags$b("Design effect:"),
                                      verbatimTextOutput(outputId = "de_crt"),
                                      tags$b("Number of clusters per group:"),
                                      verbatimTextOutput(outputId = "num_clus_crt"),
                                      plotOutput(outputId = "powerplot_mean_crt")
                                      )
                               ),
                      tabPanel("Stepped-Wedge CRT (Means)",
                               titlePanel("Stepped-Wedge Cluster Randomized Trials (Means)"),
                               column(4,
                                      wellPanel(sliderInput(inputId = "siglevel_sw", 
                                                            label = "Choose significance level (Type I error probability)",
                                                            value = 0.05, min = 0, max = 0.2, 
                                                            step = 0.005),
                                                sliderInput(inputId = "power_sw", 
                                                            label = "Choose power", 
                                                            value = 0.800, 
                                                            min = 0.5, max = 1, 
                                                            step = 0.005),
                                                numericInput(inputId = "delta_sw",
                                                             label = "Insert true difference in means", 
                                                             value = 0.8),
                                                numericInput(inputId = "sd_sw", 
                                                             label = "Insert standard deviation",
                                                             value = 1),
                                                numericInput(inputId = "clus_sw",
                                                             label = "Insert average cluster size", 
                                                             value = 25),
                                                tags$b("Use slider or text box to enter intracluster correlation coefficient:"),
                                                sliderInput(inputId = "icc_sw_slider",label = NULL,
                                                            value = 0.05, min = 0, max = 0.5, 
                                                            step = 0.001),
                                                numericInput(inputId = "icc_sw_txt",label = NULL,
                                                             value = 0.05, 
                                                             min = 0, max = 0.5),
                                                numericInput(inputId = "num_steps",label = "Enter number of steps (excluding baseline)",
                                                             value = 3,
                                                             min = 0),
                                                numericInput(inputId = "num_t", 
                                                             label = "Enter number of clusters switched at each step",
                                                             value = 15,
                                                             min = 0),
                                                numericInput(inputId = "num_base", 
                                                             label = "Enter number of baseline clusters",
                                                             value = 20,
                                                             min = 0),
                                                selectInput(inputId = "type_sw",
                                                            label = "Choose type of t test",
                                                            c("two.sample","one.sample",
                                                              "paired")),
                                                selectInput(inputId = "alt_sw",
                                                            label = "Choose one- or two-sided test",
                                                            c("two.sided", "one.sided")),
                                                HTML(paste0(
                                                  "<small>","<b>","Note:","</b>",
                                                  " For clarification on any of the parameters,",
                                                  " please refer to the 'Definitions' tab under the About menu.",
                                                  "</small>")
                                                  )
                                                )
                                      ),
                               column(8,
                                      tags$b("Sample size per group:"),
                                      verbatimTextOutput(outputId = "samplesize_sw"),
                                      tags$b("Design effect:"),
                                      verbatimTextOutput(outputId = "de_swm"),
                                      tags$b("Number of clusters per group:"),
                                      verbatimTextOutput(outputId = "num_clus_sw"),
                                      plotOutput(outputId = "powerplot_mean_sw"),
                                      plotOutput(outputId = "iccplot_mean_sw")
                                      )
                               ),
                      tabPanel("CRT (Proportions)",
                               titlePanel("Cluster Randomized Trials (Proportions)"),
                               column(4,
                                      wellPanel(sliderInput(inputId = "siglevel_crtp", 
                                                            label = "Choose significance level (Type I error probability)",
                                                            value = 0.05, min = 0, max = 0.2, 
                                                            step = 0.005),
                                                sliderInput(inputId = "power_crtp", 
                                                            label = "Choose power", 
                                                            value = 0.800, 
                                                            min = 0.5, max = 1, 
                                                            step = 0.005),
                                                tags$b("Use slider or text box to enter probability in control:"),
                                                sliderInput(inputId = "control_crtp_slider",label = NULL,
                                                            value = 0.75, min = 0, max = 1, 
                                                            step = 0.001),
                                                numericInput(inputId = "control_crtp_txt",label = NULL,
                                                             value = 0.75,
                                                             min = 0, max = 1),
                                                selectInput(inputId = "prop_type_crt",
                                                            label = "Choose",
                                                            c("risk difference",
                                                              "odds ratio",
                                                              "risk ratio",
                                                              "relative risk reduction")),
                                                uiOutput("ui_prop_crt"),
                                                numericInput(inputId = "clus_p",
                                                             label = "Insert average cluster size", 
                                                             value = 25),
                                                tags$b("Use slider or text box to enter intracluster correlation coefficient:"),
                                                sliderInput(inputId = "icc_crtp_slider",label = NULL,
                                                            value = 0.05, min = 0, max = 0.5, 
                                                            step = 0.001),
                                                numericInput(inputId = "icc_crtp_txt",label = NULL,
                                                             value = 0.05, 
                                                             min = 0, max = 0.5,step = 0.001),
                                                selectInput(inputId = "type_crtp",
                                                            label = "Choose type of t test",
                                                            c("two.sample","one.sample",
                                                              "paired")),
                                                selectInput(inputId = "alt_crtp",
                                                            label = "Choose one- or two-sided test",
                                                            c("two.sided", "one.sided")),
                                                HTML(paste0(
                                                  "<small>","<b>","Note:","</b>",
                                                  " For clarification on any of the parameters,",
                                                  " please refer to the 'Definitions' tab under the About menu.",
                                                  "</small>")
                                                )
                                      )
                               ),
                               column(8,
                                      tags$b("Sample size per group:"),
                                      verbatimTextOutput(outputId = "samplesize_prop_crt"),
                                      tags$b("Design effect:"),
                                      verbatimTextOutput(outputId = "de_crtp"),
                                      tags$b("Probability in intervention:"),
                                      verbatimTextOutput(outputId = "type_crtp"),
                                      tags$b("Number of clusters per group:"),
                                      verbatimTextOutput(outputId = "num_clus_crtp"),
                                      plotOutput(outputId = "powerplot_prop_crt")
                               )
                               ),
                      tabPanel("Stepped-Wedge CRT (Proportions)",
                               titlePanel("Stepped-Wedge Cluster Randomized Trials (Proportions)"),
                               column(4,
                                      wellPanel(sliderInput(inputId = "siglevel_swp", 
                                                            label = "Choose significance level (Type I error probability)",
                                                            value = 0.05, min = 0, max = 0.2, 
                                                            step = 0.005),
                                                sliderInput(inputId = "power_swp", 
                                                            label = "Choose power", 
                                                            value = 0.800, 
                                                            min = 0.5, max = 1, 
                                                            step = 0.005),
                                                tags$b("Use slider or text box to enter probability in control:"),
                                                sliderInput(inputId = "control_swp_slider",label = NULL,
                                                            value = 0.75, min = 0, max = 1, 
                                                            step = 0.001),
                                                numericInput(inputId = "control_swp_txt",label = NULL,
                                                             value = 0.75,
                                                             min = 0, max = 1),
                                                selectInput(inputId = "prop_type_sw",
                                                            label = "Choose",
                                                            c("risk difference",
                                                              "odds ratio",
                                                              "risk ratio",
                                                              "relative risk reduction")),
                                                uiOutput("ui_prop_sw"),
                                                numericInput(inputId = "clus_swp",
                                                             label = "Insert average cluster size", 
                                                             value = 25),
                                                tags$b("Use slider or text box to enter intracluster correlation coefficient:"),
                                                sliderInput(inputId = "icc_swp_slider",label = NULL,
                                                            value = 0.05, min = 0, max = 0.5, 
                                                            step = 0.001),
                                                numericInput(inputId = "icc_swp_txt",label = NULL,
                                                             value = 0.05, 
                                                             min = 0, max = 0.5),
                                                numericInput(inputId = "num_steps",label = "Enter number of steps (excluding baseline)",
                                                             value = 3,
                                                             min = 0),
                                                numericInput(inputId = "num_t", 
                                                             label = "Enter number of clusters switched at each step",
                                                             value = 15,
                                                             min = 0),
                                                numericInput(inputId = "num_base", 
                                                             label = "Enter number of baseline clusters",
                                                             value = 20,
                                                             min = 0),
                                                selectInput(inputId = "type_swp",
                                                            label = "Choose type of t test",
                                                            c("two.sample","one.sample",
                                                              "paired")),
                                                selectInput(inputId = "alt_swp",
                                                            label = "Choose one- or two-sided test",
                                                            c("two.sided", "one.sided")),
                                                HTML(paste0(
                                                  "<small>","<b>","Note:","</b>",
                                                  " For clarification on any of the parameters,",
                                                  " please refer to the 'Definitions' tab under the About menu.",
                                                  "</small>")
                                                )
                                      )
                               ),
                               column(8,
                                      tags$b("Sample size per group:"),
                                      verbatimTextOutput(outputId = "samplesize_swp"),
                                      tags$b("Probability in intervention:"),
                                      verbatimTextOutput(outputId = "type_swp"),
                                      tags$b("Design effect:"),
                                      verbatimTextOutput(outputId = "de_swp"),
                                      tags$b("Odds ratio:"),
                                      verbatimTextOutput(outputId = "or_swp"),
                                      tags$b("Number of clusters per group:"),
                                      verbatimTextOutput(outputId = "num_clus_swp"),
                                      plotOutput(outputId = "powerplot_prop_sw"),
                                      plotOutput(outputId = "iccplot_prop_sw")
                               )
                               )
                      ),
############################## ABOUT TAB ##########################
           navbarMenu("About",
                      tabPanel("Definitions",
                               titlePanel("Definitions"),
                               HTML(paste("<b>","Type I error:","</b>","Occurs when the null hypothesis is rejected even though it is true.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Type II error:","</b>","Occurs when the null hypothesis is failed to be rejected even though it is false.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Power:","</b>","The probability of rejecting the null hypothesis when the alternative hypothesis is true. This value is 1 - (beta), where beta is the probability of making a Type II error.")),
                               br(),
                               br(),
                               HTML(paste("<b>","significance level:","</b>","The probability of rejecting the null hypothesis given that it is true. This is also the probabiltiy of making a Type I error.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Risk difference:","</b>","The difference in proportions (probability) of the two treatment groups.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Intracluster correlation coefficient (ICC):","</b>","The degree of similarity in responses from individuals within a cluster.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Odds ratio:","</b>","The odds that an outcome will occur given an exposure, compared to the odds of the outcome in the absence of the exposure.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Risk ratio:","</b>","The ratio of probability of an outcome in the exposed group to the probability of the outcome in the control group.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Median survival time:","</b>", "The time at which the chance of surviving beyond that time is 50%.")),
                               br(),
                               br(),
                               HTML(paste("<b>","Hazard ratio:","</b>","The ratio of the hazard rates of the two treatment groups (h1/h0)."))
                               ),
                      tabPanel("Credits",
                               titlePanel("Credits"),
                               HTML(paste("<b>","Conceptualization","</b>")),
                               br(),
                               HTML("Bruno R da Costa"),
                               br(),
                               br(),
                               HTML(paste("<b>","Programming","</b>")),
                               br(),
                               HTML("Shruthi Vaidyanathan"),
                               br(),
                               br(),
                               HTML(paste("<b>","Design and Development","</b>")),
                               br(),
                               HTML("Shruthi Vaidyanathan"),
                               br(),
                               HTML("Bruno R da Costa"),
                               br(),
                               HTML("Kevin Thorpe"),
                               br(),
                               br(),
                               HTML(paste("<b>","Contact","</b>")),
                               br(),
                               HTML("Bruno R da Costa"),
                               br(),
                               tags$a("bruno.dacosta@utoronto.ca", 
                                      href = "mailto:bruno.dacosta@utoronto.ca"),
                               br(),
                               br(),
                               br(),
                               tags$img(src = 'ahrc-banner-2-1.png',width = 315,height = 105),
                               tags$img(src = 'uhn.jpg',width = 315,height = 71)
                               )
                      )
           )


# *Input() functions,
# *Output() functions
